// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSo4l_JgMraHQOa446B9AefmYUXFWAmoU',
    appId: '1:307923968626:web:693fc3b0e558301ab198eb',
    messagingSenderId: '307923968626',
    projectId: 'emote-3df9d',
    authDomain: 'emote-3df9d.firebaseapp.com',
    storageBucket: 'emote-3df9d.firebasestorage.app',
    measurementId: 'G-LD5M4J7ZL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqsQD6YiaLYIWKaQ93v2dLGomLLNjB62A',
    appId: '1:307923968626:android:6108bff9a8d5657bb198eb',
    messagingSenderId: '307923968626',
    projectId: 'emote-3df9d',
    storageBucket: 'emote-3df9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUn1yyWxNWScaJfV-VlXceqPude1nSdWY',
    appId: '1:307923968626:ios:e945d3440a789a40b198eb',
    messagingSenderId: '307923968626',
    projectId: 'emote-3df9d',
    storageBucket: 'emote-3df9d.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUn1yyWxNWScaJfV-VlXceqPude1nSdWY',
    appId: '1:307923968626:ios:e945d3440a789a40b198eb',
    messagingSenderId: '307923968626',
    projectId: 'emote-3df9d',
    storageBucket: 'emote-3df9d.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSo4l_JgMraHQOa446B9AefmYUXFWAmoU',
    appId: '1:307923968626:web:2ef370ecd25a68dab198eb',
    messagingSenderId: '307923968626',
    projectId: 'emote-3df9d',
    authDomain: 'emote-3df9d.firebaseapp.com',
    storageBucket: 'emote-3df9d.firebasestorage.app',
    measurementId: 'G-0WZ0QLS636',
  );
}
